---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "remove dependencies that are no longer required"
    become: yes
    apt:
      autoremove: yes

  - name: "install nodejs and npm"
    become: yes
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: "install n"
    become: yes
    npm:
      name: n
      global: yes
      production: yes

  - name: "install nodejs 13.8.0"
    become: yes
    shell: n 13.8.0

  - name: run migerations
    shell: |
        cd backend
        sudo npm install
        sudo npm run migrations > migration_status 
        if grep -q "has been executed successfully" migration_status
        then
          echo "DB migration was successful, will update memstash..."
          curl -H "Content-Type: text/plain" -H "token: e4eb2ece-7512-4ace-85dc-bc851a1cf516" --request PUT --data "success" https://api.memstash.io/values/DB_MIGRATION_${CIRCLE_WORKFLOW_ID:0:7}
        else
          echo "DB migration failed, please verify setup! Probably the database already exists. Verify setup!"
          curl -H "Content-Type: text/plain" -H "token: 09307427-b13e-44a4-9372-357a0b1f40a2" --request PUT --data "failure" https://api.memstash.io/values/DB_MIGRATION_${CIRCLE_WORKFLOW_ID:0:7}
        fi
        echo "WorkflowID=${CIRCLE_WORKFLOW_ID:0:7}"    
  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present
